# Generated by Django 3.2.18 on 2023-06-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarycomment',
            options={'ordering': ['created_at']},
        ),
    ]
