# Generated by Django 3.2.18 on 2023-06-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryshare',
            old_name='shared_at',
            new_name='created_at',
        ),
    ]
