# Generated by Django 3.2.18 on 2023-05-31 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarycomment',
            name='diary',
        ),
        migrations.RemoveField(
            model_name='diarycomment',
            name='group',
        ),
        migrations.AddField(
            model_name='diarycomment',
            name='share',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diaries.diaryshare'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryemote',
            name='share',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diaries.diaryshare'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaryemote',
            name='emotion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='diaryemote',
            unique_together={('user', 'share')},
        ),
        migrations.RemoveField(
            model_name='diaryemote',
            name='diary',
        ),
    ]
