# Generated by Django 3.2.18 on 2023-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('diaries', '0002_auto_20230531_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='share',
            field=models.ManyToManyField(related_name='group_diaries', through='diaries.DiaryShare', to='groups.Group', verbose_name='shared diary to group'),
        ),
    ]
