# Generated by Django 3.2.18 on 2023-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_rename_shared_at_diaryshare_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
