# Generated by Django 3.2.18 on 2023-06-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedules', '0001_initial_squashed_0004_alter_calendar_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='content_type',
            new_name='owner_content_type',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='object_id',
            new_name='owner_object_id',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('owner_content_type', 'owner_object_id')},
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='title',
        ),
    ]
