# Generated by Django 3.2.18 on 2023-06-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='color',
        ),
    ]
