# Generated by Django 3.2.18 on 2023-06-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20230608_1312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['owner_content_type', 'owner_object_id'], name='schedules_c_owner_c_51eec4_idx'),
        ),
    ]
