# Generated by Django 3.2.18 on 2023-06-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedules', '0003_auto_20230608_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='owner_content_type',
            field=models.ForeignKey(editable=False, limit_choices_to=models.Q(models.Q(('app_label', 'accounts'), ('model', 'user')), models.Q(('app_label', 'groups'), ('model', 'group')), _connector='OR'), on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='owner_object_id',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
